export type CharacterProfileType = {
  CharacterClassName: string;
  CharacterImage: string;
  CharacterLevel: number;
  CharacterName: string;
  ExpeditionLevel: number;
  GuildMemberGrade: string;
  GuildName: string;
  ItemAvgLevel: string;
  ItemMaxLevel: string;
  PvpGradeName: string;
  ServerName: string;
  Stats: any[];
  Tendencies: any[];
  Title: string;
  TotalSkillPoint: number;
  TownLevel: number;
  TownName: string;
  UsingSkillPoint: number;
};
